# Generated by Django 5.1.3 on 2024-11-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("function", models.CharField(max_length=100)),
                ("eps", models.FloatField()),
                ("results", models.JSONField(default=None, null=True)),
            ],
        ),
    ]
